# Generated by Django 4.0.5 on 2022-07-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('slno', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nane', models.CharField(max_length=30)),
                ('rollno', models.BigIntegerField()),
                ('phno', models.CharField(max_length=10)),
            ],
        ),
    ]
